language: java
os:
- osx
before_install:
- wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.2-bin.tar.gz
- tar -xzf apache-ant-1.10.2-bin.tar.gz
- export PATH=`pwd`/apache-ant-1.10.2/bin:$PATH
script:
- ant
- rm -rf apache-ant*