language: java
os:
- osx
before_install:
- wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.2-bin.tar.gz
- tar -xzvf apache-ant-1.10.2-bin.tar.gz
- export PATH=`pwd`/apache-ant-1.10.2/bin:$PATH
- cd JavaDesktopAppProjectTemplate
script:
- ant
- rm ../apache-ant-1.10.2-bin.tar.gz
- rm -rf ../apache-ant-1.10.2
deploy:
  provider: releases
  api_key:
    secure: yXVi1b05dFPWuRDF_5ilsw
  file: 
    - dist/MyApp4Mac.dmg
    - dist/MyApp4Win.zip
  skip_cleanup: true
  name: Build $(date +'%d.%m.%Y %R')
  on:
    repo: vorachet/JavaDesktopAppProjectTemplate
